CREATE TABLE check_ins (
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attendee_id INTEGER NOT NULL,

    CONSTRAINT check_ins_attendee_id_fk FOREIGN KEY (attendee_id)
    REFERENCES attendees (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- IDENTITY = AUTO_INCREMENT